### ISSUE TITLE
Terrain and GPS accuracy questions

### ISSUE THREAD

**Issue by garudaonekh** [Twisted-Fields/acorn-precision-farming-rover#2]
hi,
The  farm terrain are normally very rough, muddy and difficult to drive thru. What is your suggestion?

my second concern is GPS accuracy, especially in my country. If it is only 1 meter wrong, it will step on the crop. I see some vehicle use line tracking, I donot know if this a good option?

Thanks.

**Comment by tlalexander** [comment]
Hello!

The best place to ask questions like this is on our community forum at [community.twistedfields.com](https://community.twistedfields.com)

Our vehicle does well in mud because it is lightweight. But you might want to experiment with wider tires. Our GPS uses RTK GPS which probably works in other countries. It should provide 15cm accuracy.

I will close this issue but do post on the community forum if you have additional questions. Thank you!
