### ISSUE TITLE
unable to activate autonomy

### ISSUE THREAD

**Issue by jojowork** [Twisted-Fields/acorn-precision-farming-rover#25]
I am trying out your simulation
`./run_docker_simulation.sh` starts up the two docker-containers as described.
I can open the UI on localhost:80
As a next step I selected the path: `aaa_test` and clicked on load path. The loaded path of acorn is updated

```
Data Age: -32398.7 sec
Voltage: 46.62
Speed: 0
Control State: Autonomy failed - too far from path.
Motor State: Motors enabled.
Loaded Path Name: around_barn_gps 
Autonomy Allowed: false
Autonomy Active: false
Access Point: null
Wifi Signal: null dBm
```
But I seem to be unable to activate autonomy (button is not clickable) and acorn1 does not leave the `Autonomy failed - too far from path.` state. What am I doing wrong? I would have expected the sample-files to be within the range of what Acorn is capable of driving to. And to me it seems pretty unclear how I can create a new path within the UI. Any proposals?

**Comment by tlalexander** [comment]
Hello and welcome to the project! Sorry about that. We don't have a lot of users yet and sometimes I break things. I will need to start using a stable branch and a development branch to prevent that.

In simulation it should automatically warp to the location of newly loaded paths, so something is wrong. I will try to take a look at this in the next few days and see if I can get you situated by end of week if not sooner. I appreciate your interest! I may be able to look at this today, and probably the fix is not complicated. I will update here when I know more. Thanks!

**Comment by jojowork** [comment]
Hi @tlalexander 
Thanks for the fast response. 
I will try it out tomorrow i guess and can then report you.

**Comment by jojowork** [comment]
I pulled the last recent version and tried it again.
This time it worked and the rover is following the path.
Nice work! :)

**Comment by tlalexander** [comment]
Wonderful I am glad I was able to help!
